### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by TysonNgo** [TysonNgo/splice-up#1]
# gui
-----

```
______________________
|o===========o o=====o|
||           | |     |<-- video list
|| video     | |     ||
||           | |     ||
|o===========o o=====o|
|speed x __   [export]|
|---------------------|
|[=========%=========]|
|progress info        |
‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
```

video list items

```
 ________________________
|thumb| some/path/to/vid |
...
```

### form
- [x] video preview container
- [x] video list (these contain the video paths)
- [x] speed up multiplier
- [x] export button (~~saves output file to some temp location, then brings up download popup?—not sure if possible~~)
- [x] % progress bar with additional information (bitrate, filesize, etc.)

### functionality
- [x] gui export button -> send message from ipc renderer to tell the program to process/export the sped up spliced video(s)

##### video list
- [x] item removable
- [x] item drag and drop to reorganize

# backend
----

- [x] ipc main receives message and calls ffmpeg subprocess
- [x] ffmpeg subprocess sends progress to a local tcp port
- [x] send tpc data to ipc 

# sass
----

- [x] `ul/li` for video list
- [x] `video` for currently selected video from video list preview
- [x] speed multiplier input box
- [x] submit button
- [x] animation on progress bar

# additional things
----

- video list sort button
- video list clear button

should be able to run cross-platform, just need to run the correct ffmpeg binary
